version: "3.8"

services:
  db:
    image: postgres:15.4-alpine
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - internal_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # ports:
    #   - "3001:3001"
    depends_on:
      - db
    networks:
      - internal_network
      - external_network
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
      # ports:
      #   - "80:80"
      # - "3000:3000"
    depends_on:
      - api
    networks:
      - internal_network
      - external_network
    restart: unless-stopped

networks:
  internal_network:
    driver: bridge
  external_network:
    external: true
