version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:18

    restart: unless-stopped

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:db

  db:
    image: postgres:15.4-alpine
    restart: unless-stopped
    volumes:
      - ../database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
