version: '3.8'

services:
  app:
    # image: node:18.17.0-alpine
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    ports:
      - "${HOST_API_PORT}:${API_PORT}"
      - "${HOST_CLIENT_PORT}:5173"
    volumes:
      - ../../:/workspaces/:cached
    command: sleep infinity

  db:
    image: postgres:14.8-alpine
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
