version: '3.8'

services:
  app:
    # image: node:18.17.0-alpine
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - ../../:/workspaces/:cached
    command: sleep infinity

  db:
    image: postgres:14.8-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pokemon
