version: '3.8'

services:
  app:
    # image: node:18.17.0-alpine
    image: mcr.microsoft.com/devcontainers/javascript-node:1-18-bullseye
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/home/api
    command: sleep infinity

  db:
    image: postgres:14.8-alpine
    restart: unless-stopped
    # ports:
    #   - "${DB_PORT}:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
